"""Add address to companies

Revision ID: 1b862d61f097
Revises: cbab4a6dc3b6
Create Date: 2026-02-13 21:07:04.195003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b862d61f097'
down_revision: Union[str, Sequence[str], None] = 'cbab4a6dc3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'address')
    # ### end Alembic commands ###
