"""source

Revision ID: a69c0c89bb97
Revises: b3c9b90bbc58
Create Date: 2026-02-18 18:33:54.969613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69c0c89bb97'
down_revision: Union[str, Sequence[str], None] = 'b3c9b90bbc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('source', sa.String(), nullable=True))
    op.create_index(op.f('ix_reviews_source'), 'reviews', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_source'), table_name='reviews')
    op.drop_column('reviews', 'source')
    # ### end Alembic commands ###
