"""Split urls and add source

Revision ID: b3c9b90bbc58
Revises: 1b862d61f097
Create Date: 2026-02-18 15:31:42.736319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c9b90bbc58'
down_revision: Union[str, Sequence[str], None] = '1b862d61f097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('url_yandex', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('url_2gis', sa.String(), nullable=True))
    op.drop_index(op.f('ix_companies_url'), table_name='companies')
    op.drop_column('companies', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_companies_url'), 'companies', ['url'], unique=True)
    op.drop_column('companies', 'url_2gis')
    op.drop_column('companies', 'url_yandex')
    # ### end Alembic commands ###
