"""Add sentiment to reviews

Revision ID: c1677672b1fd
Revises: 00252f7cd6e8
Create Date: 2025-11-23 17:16:15.479311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1677672b1fd'
down_revision: Union[str, Sequence[str], None] = '00252f7cd6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('sentiment', sa.String(), nullable=True))
    op.create_index(op.f('ix_reviews_sentiment'), 'reviews', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_sentiment'), table_name='reviews')
    op.drop_column('reviews', 'sentiment')
    # ### end Alembic commands ###
